# Generated by Django 4.1.3 on 2022-11-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='This product has no description')),
                ('photo', models.ImageField(upload_to='products')),
                ('size', models.CharField(default='0x0x0мм', max_length=100)),
                ('price', models.FloatField(max_length=10)),
            ],
        ),
    ]
